management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: "*"
    metrics:
        export:
            graphite:
                enabled: false
            prometheus:
                enabled: true
            simple:
                enabled: false

spring:
  main:
    banner-mode: "off"
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: ${spring.application.name}


server:
  port: 8196
  ssl:
    key-store-type: PKCS12
    key-store: /var/lm/keystore/keystore.p12
    key-store-password: password
    key-alias: velocloud-sdwan-driver
    enabled: true
    
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.ibm.sdwan: DEBUG

rcdriver:
  topics:
    lcmOpOccPollingTopic: lcm_op_occ_polling_requests
    lifecycleResponsesTopic: lm_vnfc_lifecycle_execution_events
    pollingEdgeStatusTopic: polling_edge_status_events

